Use the system classloader as parent
Fixes java.lang.NoClassDefFoundError when running on a Java 9 JVM.
Google-Java-Format does not yet have proper Java 9 module support and
doesn't declare required runtime dependencies.
By using the system classloader as parent classloader, the required
classes can be found nevertheless.